version: '3.3'

services:
  pgdb:
    image: postgres:9.5-alpine
    container_name: postgres
    volumes:
      - "./sourcefiles/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_ROOT_PASSWORD=uaQYs4E34q9k
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=uaQYs4E34q9k
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"

networks:
  mynet:
    driver: bridge